### ISSUE TITLE
Bug on opening KeyUI

### ISSUE THREAD

**Issue by nancikennedy** [1onar/KeyUI#1]
On Retail, using v2.02 KUI

21x KeyUI/KeyUI.lua:350: attempt to index field 'MouseFrame' (a nil value)
[string "@KeyUI/KeyUI.lua"]:350: in function `SwitchBoardMouse'
[string "@KeyUI/KeyUI.lua"]:532: in function `RefreshKeys'
[string "@KeyUI/KeyUI.lua"]:103: in function `Load'
[string "@KeyUI/KeyUI.lua"]:35: in function `OnClick'
[string "@Masque/Libs/LibDBIcon-1.0-52/LibDBIcon-1.0.lua"]:170: in function <...eMasque/Libs/LibDBIcon-1.0/LibDBIcon-1.0.lua:168>

Locals:
self = <table> {
 CreateMouseUI = <function> defined @KeyUI/MouseKeyUI.lua:42
 controlsFrame = KBControlsFrame {
 }
 GetMouseholder = <function> defined @KeyUI/KeyUI.lua:160
 CreateChangerDDMouse = <function> defined @KeyUI/KeyUI.lua:789
 ddChangerMouse = KBChangeBoardDDMouse {
 }
 modif = <table> {
 }
 CreateControls = <function> defined @KeyUI/UIKeyboard.lua:46
 tooltip = KeyUITooltip {
 }
 SaveLayout = <function> defined @KeyUI/MouseKeyUI.lua:319
 keyboardFrame = KeyUIMainFrame {
 }
 SaveMouse = <function> defined @KeyUI/MouseKeyUI.lua:8
 SaveKeyboard = <function> defined @KeyUI/UIKeyboard.lua:9
 CreateDropDown = <function> defined @KeyUI/KeyUI.lua:712
 SwitchBoardMouse = <function> defined @KeyUI/KeyUI.lua:346
 GetMouse = <function> defined @KeyUI/KeyUI.lua:175
 RefreshKeys = <function> defined @KeyUI/KeyUI.lua:515
 GetMouseControls = <function> defined @KeyUI/KeyUI.lua:182
 CreateMouseControls = <function> defined @KeyUI/MouseKeyUI.lua:57
 BattleCheck = <function> defined @KeyUI/KeyUI.lua:853
 ButtonMouseOver = <function> defined @KeyUI/KeyUI.lua:206
 LoadDropDown = <function> defined @KeyUI/KeyUI.lua:107
 NewButtonMouse = <function> defined @KeyUI/MouseKeyUI.lua:349
 SetKey = <function> defined @KeyUI/KeyUI.lua:433
 CreateTooltip = <function> defined @KeyUI/KeyUI.lua:189
 CreateChangerDD = <function> defined @KeyUI/KeyUI.lua:751
 LoadSpells = <function> defined @KeyUI/KeyUI.lua:112
 CheckModifiers = <function> defined @KeyUI/KeyUI.lua:399
 ddChanger = KBChangeBoardDD {
 }
 dropdown = KBDropDownMouse {
 }
 spells = <table> {
 }
 CreateKeyboard = <function> defined @KeyUI/UIKeyboard.lua:14
 CreateMouseholder = <function> defined @KeyUI/MouseKeyUI.lua:13
 RefreshControls = <function> defined @KeyUI/UIKeyboard.lua:40
 NewButton = <function> defined @KeyUI/KeyUI.lua:230
 menu = <table> {
 }
 GetKeyboard = <function> defined @KeyUI/KeyUI.lua:138
 SwitchBoard = <function> defined @KeyUI/KeyUI.lua:297
 GetControls = <function> defined @KeyUI/KeyUI.lua:153
 Load = <function> defined @KeyUI/KeyUI.lua:58
 CreateDropDownMouse = <function> defined @KeyUI/KeyUI.lua:723
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'MouseFrame' (a nil value)"
addonOpen = true

**Comment by 1onar** [comment]
Should be fixed now in v2.0.3.
Thanks for reaching out to me. May you have a look and can confirm its fixed?
