### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by ryanwills720** [1onar/KeyUI#25]
Add the traditional 1800 keyboard layout.

https://www.keebtalk.com/t/1800-layout-96-layout-full-size-compact-catch-all/16593 

I personally use this with the drop SHIFT keyboard. 

https://drop.com/buy/drop-shift-mechanical-keyboard

**Comment by 1onar** [comment]
Thank you for bringing this layout to my attention. I'll make sure to add it soon!

**Comment by 1onar** [comment]
You may have a look at the newest release. I think i done it right.
