### ISSUE TITLE
Mouse Button 4 and 5?

### ISSUE THREAD

**Issue by goldenpipes** [1onar/KeyUI#4]
Good Tidings!

What a wonderful addon!

That said, is it possible to have other layouts?  I seem to be unable to bind 'Mouse 4' and 'Mouse 5'.

Thanks!

**Comment by 1onar** [comment]
Hello there,
binding button "Button4" and "Button5" which are Mouse Button 4 and Mouse Button 5 working as intended in my game.  Maybe your Mouse Software did bind something else?
