### ISSUE TITLE
Druid forms not shifting displayed skills

### ISSUE THREAD

**Issue by AGeekInside** [1onar/KeyUI#5]
The UI display for skills doesn't seem to update when the character is in a different form and the main bar changes to reflect skills for the new form. The first image shows the UI displaying the correct skills. The second shows that KeyUI didn't update, when the character switches to Moonkin form.

![image](https://github.com/user-attachments/assets/b905a662-d1bf-4b05-b191-938069fa8eb3)

![image](https://github.com/user-attachments/assets/215ff2e6-4b88-4180-a64d-2443002b095c)

**Comment by 1onar** [comment]
Sorry for the delay.. Had to think a bit about it and test alot. Finally i have done it. You may have a look at it.
